CREATE DATABASE chapter;
GO

USE chapter;
GO

CREATE TABLE Users (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME2 DEFAULT GETDATE()
);
