CREATE DATABASE chapter;
GO

USE chapter;
GO

CREATE TABLE Users (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME2 DEFAULT GETDATE()
);

ALTER TABLE Users
ADD Role NVARCHAR(20) NOT NULL DEFAULT 'client';

UPDATE Users SET Role = 'admin' WHERE Email = 'katarina123@gmail.com';

CREATE TABLE Services(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	DurationMinutes INT NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE Employees(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Email NVARCHAR(255),
	CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE EmployeeServices(
	EmployeeId INT NOT NULL,
	ServiceId INT NOT NULL,
	PRIMARY KEY (EmployeeId, ServiceId),
	FOREIGN KEY (EmployeeId) REFERENCES Employees(Id) ON DELETE CASCADE,
	FOREIGN KEY (ServiceId) REFERENCES Services(Id) ON DELETE CASCADE
);

CREATE TABLE Bookings(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ClientId INT NOT NULL,
	EmployeeId INT NOT NULL,
	ServiceId INT NOT NULL,
	StartTime DATETIME2 NOT NULL,
	EndTime DATETIME2 NOT NULL,
	FOREIGN KEY (ClientId) REFERENCES Users(Id),
	FOREIGN KEY (EmployeeId) REFERENCES Employees(Id) ON DELETE CASCADE,
	FOREIGN KEY (ServiceId) REFERENCES Services(Id)
);